### ISSUE TITLE
Impressive work!

### ISSUE THREAD

**Issue by ckqqqq** [xinyanghuang7/Basic-Vision-Language-Model#1]
Impressive work! Could you share the training log or the training time? Is it possible to train the MLM in 4 A6000 GPU (4*40GB) in 2 days?

**Comment by xinyanghuang7** [comment]
![image](https://github.com/xinyanghuang7/Basic-Visual-Language-Model/assets/75032525/0f103ae2-f716-4ff3-b88e-0bf14178e319)



I trained for 16 hours on 4 A800 GPUs. However, I believe that training on 4 A6000 GPUs (4*40GB) might only take around 16 hours as well. I will upload the necessary configuration and time details later.

The content in the screenshot can serve as a reference for memory usage. There are many ways to reduce memory usage, such as adjusting the batch size or lowering the dimensions of LoRA, etc. However, given your expertise, you should try more comprehensive multimodal large model code repositories, such as LLAVA. This repository is a simplified version released for beginners like us. Obviously, many features are still not perfect.

🙆‍♂️
